### ISSUE TITLE
Download probability files on demand

### ISSUE THREAD

**Issue by sbliven** [elkeschaper/tral#29]
We currently require manually downloading the pvalue directory from ftp://ftp.vital-it.ch/papers/vital-it/Bioinformatics-Schaper/ into ~/.tral. This is [documented](https://acg-team.github.io/tral/configure.html#configure) but easy to miss. Failing to do so produces opaque exceptions.

We should:
- Centralize access to data files through a single function
- Automatically download single files as needed
- Provide better error messages when a file is not available. This can happen for custom scores, upon download failures, if internet is unavailable, etc.
- Mention pvalue.tar on the 'install' page
- Mirror data from ftp://ftp.vital-it.ch/papers/vital-it/Bioinformatics-Schaper/ to github to eliminate vital-it dependence.

**Comment by LinaNaef** [comment]
- better documentation 
- error messages implemented
- data too big to mirror to github; therefore not possible to store p-value files on github
Still open:
- automatically doewnload single files as needed
- new place to store data

**Comment by sbliven** [comment]
Is this solved by #38?

**Comment by matteodelucchi** [comment]
solved with new server for p-values:
https://acg-team.ulozezoz.myhostpoint.ch/pvalue.tar.gz
