### ISSUE TITLE
Website broken documentation pages

### ISSUE THREAD

**Issue by ashrosewood** [elkeschaper/tral#43]
The documentation links appear to be broken for all APIs on the code docs page of the website. https://acg-team.github.io/tral/code_docs.html.

**Comment by matteodelucchi** [comment]
Thanks for reporting the issue. The linked files were mistakenly deleted somewhere in the development process. I just restored them for now but still have to check them for correctness.

**Comment by matteodelucchi** [comment]
Updated external links to references and some internal ones. Let me know if there's anything else that is not working or not correct.

**Comment by ashrosewood** [comment]
Awesome, thanks for your quick response 👏
