### ISSUE TITLE
deprecated links third party software

### ISSUE THREAD

**Issue by matteodelucchi** [elkeschaper/tral#45]
MAFFT and TRUST can't be installed through the easysetup anymore, as their package download links are broken. The installation script doesn't catch the errors.

**Comment by matteodelucchi** [comment]
MAFFT server has been restarted and the link is working again.

**Comment by matteodelucchi** [comment]
Still waiting for a response from the developers of TRUST...

**Comment by matteodelucchi** [comment]
Still waiting for a response from the developers of TRUST...

**Comment by sbliven** [comment]
Fixed in #49 (e8594f5)
