### ISSUE TITLE
tutorial. how to run tral..... error while running python3 example_workflow_MBE2014.py.  FileNotFoundError: [Errno 2] No such file or directory: 'ginsi'

### ISSUE THREAD

**Issue by jekang39** [elkeschaper/tral#51]
Hello
Thank you for making such useful tool for free. I tried to find tutorial explaining on how to run the program, but could not find any. could you kindly let me know where I can find one? I encountered an error while running example_workflow_MBE2014.py. it may not be correct way to run the program though. it would be very helpful to read tutorial if you have one.
following is the error.... thank you again for the software.

tral.hmm.hmm_viterbi:DEBUG:  The tandem repeat is shifted by: 47
Traceback (most recent call last):
  File "example_workflow_MBE2014.py", line 141, in <module>
    sample_MBE_2014_pipeline()
  File "example_workflow_MBE2014.py", line 61, in sample_MBE_2014_pipeline
    test_pfam_list = test_seq.detect(lHMM=test_pfam_hmm)
  File "/home/jekang39/anaconda3/envs/tral/lib/python3.8/site-packages/tral-2.0.1.dev0-py3.8.egg/tral/sequence/sequence.py", line 145, in detect
    aligned_msa = repeat_align.realign_repeat(unaligned_msa, initial_alignment, sequence_type, user_path=user_path)
  File "/home/jekang39/anaconda3/envs/tral/lib/python3.8/site-packages/tral-2.0.1.dev0-py3.8.egg/tral/repeat/repeat_align.py", line 86, in realign_repeat
    p = subprocess.Popen([REPEAT_CONFIG['ginsi'],
  File "/home/jekang39/anaconda3/envs/tral/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/jekang39/anaconda3/envs/tral/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ginsi'

**Comment by matteodelucchi** [comment]
Hi jekang39

Maybe [this tutorial](https://acg-team.github.io/tral/cphmm.html) helps you. 

Looking a bit more in detail to your output: 
You're using the ginsi global realigner from MAFFT which is the standard realigner in TRAL (see [here](https://acg-team.github.io/tral/configure.html#realign-tandem-repeat-units)). It looks to me, that TRAL doesn't find your MAFFT installation ([here](https://acg-team.github.io/tral/install_external.html#mafft) is a tutorial on how you configure TRAL with external software). Try to specify it explicitly in the config file (for details see the first link). 
Note, that there are also other realigners available.
If you still encounter issues with external software, consider to use TRAL within the [docker package](https://github.com/acg-team/tral/pkgs/container/tral%2Ftral_docker).
